### ISSUE TITLE
Update Brew

### ISSUE THREAD

**Issue by tnmdynamiq** [patrickkfkan/patreon-dl#10]
Your most recent update was not yet updated on HomeBrew, if that's in your control would you mind pushing to it? The update you pushed was the issue I raised a month or so back and it would be great to have it. Also if there is another way to contact you in the future, would you mind providing so I do not bother you here? I appreciate it, thank you!

**Comment by patrickkfkan** [comment]
I've only published this via NPM.  Wasn't even aware there's a HomeBrew package for it.

**Comment by tnmdynamiq** [comment]
I ended up figuring it out. I didn't realise it was because npm is installed by brew.. Anyway I'm dumb.
