### ISSUE TITLE
Was working yesterday but not anymore

### ISSUE THREAD

**Issue by dotmick** [patrickkfkan/patreon-dl#14]
Hi there,

First of all, thanks for creating and sharing such a useful tool. really appreciate.

I've tested it yesterday and it worked perfectly, just by using:

`patreon-dl https://www.patreon.com/[creator]/posts`

I've tried the same command today and ended up being stuck on `info: PostDownloader: Fetch target post`. So I've read about cookies (which I didn't specify yesterday) and copied/pasted its value as suggested:

`patreon-dl https://www.patreon.com/posts/project-files-100875769 -c "patreon_device_id=XXXX; patreon_location_country_code=XX; patreon_locale_code=xx-XX; __cf_bm=XXXX; patreon_currency_pref=XXX; a_csrf=XXXX; analytics_session_id=XXX; __ssid=XXX; session_id=XXX"`

And end up with the following:

`info: PostDownloader: Targeting post #100875769
Apr 15 11:12:18: info: PostDownloader: Fetch target post
Apr 15 11:17:21: error: PostDownloader: Error requesting API URL "https://www.patreon.com/api/posts/100875769?include=campaign%2Caccess_rules%2Cattachments%2Caudio%2Caudio_preview.null%2Cimages%2Cmedia%2Cnative_video_insights%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Cuser%2Cuser_defined_tags%2Cti_checks&sort=-published_at&json-api-version=1.0&filter%5Bcontains_exclusive_posts%5D=true&filter%5Bis_draft%5D=false":  (FetcherError) request to https://www.patreon.com/api/posts/100875769?include=campaign%2Caccess_rules%2Cattachments%2Caudio%2Caudio_preview.null%2Cimages%2Cmedia%2Cnative_video_insights%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Cuser%2Cuser_defined_tags%2Cti_checks&sort=-published_at&json-api-version=1.0&filter%5Bcontains_exclusive_posts%5D=true&filter%5Bis_draft%5D=false failed, reason: connect ETIMEDOUT 2606:4700::6810:180e:443 (retried 3 times)
Apr 15 11:17:21: error: PostDownloader: Failed to fetch posts
Apr 15 11:17:21: warn: PostDownloader: End with error
Apr 15 11:17:21: warn: PostDownloader end with error`

When I try to open "https://www.patreon.com/api/posts/100875769?include=campaign%2Caccess_rules%2Cattachments%2Caudio%2Caudio_preview.null%2Cimages%2Cmedia%2Cnative_video_insights%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Cuser%2Cuser_defined_tags%2Cti_checks&sort=-published_at&json-api-version=1.0&filter%5Bcontains_exclusive_posts%5D=true&filter%5Bis_draft%5D=false" in the browser, it works. Cookie issue?

Any idea on how to fix this? Have I missed something?

**Comment by patrickkfkan** [comment]
Hi, are you still having this issue? I just tested the link to the post and it works fine (although I only got image previews as I'm not a subscriber). `ETIMEDOUT` sounds like a network issue rather than something with `patreon-dl` itself...

**Comment by dotmick** [comment]
Hi, thanks for coming back to me. False alarm, I had to reset my network and terminal and it's all good now. Thanks again and great tool btw!

PS: got another question/feature request but will create a new discussion.
