### ISSUE TITLE
Failed to fetch posts

### ISSUE THREAD

**Issue by EvilMir** [patrickkfkan/patreon-dl#17]
hello
I use clash(VPN)  and can access patreon successfully
but can't download
what should I do?

my command
`patreon-dl "https://www.patreon.com/posts/minnie-8k-3d-vr-102928930" -c "patreon_device_id=xxx; _ketch_consent_v1_=xxx; __ssid=xxx; patreon_locale_code=xxx; patreon_location_country_code=xx; _gid=xxx7; _ga=xxx; patreon_currency_pref=xxx; g_state=xxx; group_id=xxx; session_id=xxxI; __cf_bm=xxx; analytics_session_id=xxx; _ga_JF55G82FNT=xxx" -o "F:\"`

`May 03 12:51:50: info: PostDownloader: Targeting post #102928930
May 03 12:51:50: info: PostDownloader: Fetch target post
May 03 12:51:51: error: PostDownloader: Error requesting API URL "https://www.patreon.com/api/posts/102928930?include=campaign%2Caccess_rules%2Cattachments%2Caudio%2Caudio_preview.null%2Cimages%2Cmedia%2Cnative_video_insights%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Cuser%2Cuser_defined_tags%2Cti_checks&sort=-published_at&json-api-version=1.0&filter%5Bcontains_exclusive_posts%5D=true&filter%5Bis_draft%5D=false":  (FetcherError) request to https://www.patreon.com/api/posts/102928930?include=campaign%2Caccess_rules%2Cattachments%2Caudio%2Caudio_preview.null%2Cimages%2Cmedia%2Cnative_video_insights%2Cpoll.choices%2Cpoll.current_user_responses.user%2Cpoll.current_user_responses.choice%2Cpoll.current_user_responses.poll%2Cuser%2Cuser_defined_tags%2Cti_checks&sort=-published_at&json-api-version=1.0&filter%5Bcontains_exclusive_posts%5D=true&filter%5Bis_draft%5D=false failed, reason:  (retried 3 times)
May 03 12:51:51: error: PostDownloader: Failed to fetch posts
May 03 12:51:51: warn: PostDownloader: End with error
May 03 12:51:51: warn: PostDownloader end with error
There were errors processing the following URLs: [
  "https://www.patreon.com/posts/minnie-8k-3d-vr-102928930"
]`

**Comment by patrickkfkan** [comment]
I don't have Clash VPN for testing but a quick search reveals something about enabling "Global mode" in Clash. Default seems to be "split mode" which requires setting `http_proxy` env variable - but this is not supported atm by `patreon-dl`. Did you try "global mode"?
