### ISSUE TITLE
this url format not support [https://www.patreon.com/user/posts?u=userId]

### ISSUE THREAD

**Issue by cyberskycat** [patrickkfkan/patreon-dl#18]
request url: https://www.patreon.com/user/posts?u=80821958

detail log

> May 06 20:18:54: info: PostDownloader: Targeting posts by 'user'
> May 06 20:18:54: debug: PostDownloader: Fetch initial data from "https://www.patreon.com/user"
> May 06 20:18:55: debug: PageParser: Parse initial data from https://www.patreon.com/user
> May 06 20:18:55: debug: PageParser: Trying pattern: /window\.patreon\s*?=\s*?({.+?});/gm
> May 06 20:18:55: debug: PageParser: No match for pattern: /window\.patreon\s*?=\s*?({.+?});/gm
> May 06 20:18:55: debug: PageParser: Trying pattern: /<script id="__NEXT_DATA__" type="application\/json">(.+)<\/script>/gm
> May 06 20:18:55: debug: PostDownloader: Initial data: campaign ID 'undefined'; current user ID '127971141'
> May 06 20:18:55: error: PostDownloader: Campaign ID not found in initial data of "https://www.patreon.com/user"
> May 06 20:18:55: warn: PostDownloader end with error

**Comment by patrickkfkan** [comment]
Updated v1.5.0. Added support for URL format `https://www.patreon.com/user/posts?u=userId`. Please try again with this version.

Closing this issue for now. If the new version doesn't resolve the issue for you, feel free to re-open it or start a new one.

**Comment by cyberskycat** [comment]
> Updated v1.5.0. Added support for URL format `https://www.patreon.com/user/posts?u=userId`. Please try again with this version.
> 
> Closing this issue for now. If the new version doesn't resolve the issue for you, feel free to re-open it or start a new one.

thanks ,version 1.5.0 works
