### ISSUE TITLE
Campaign ID not found in initial data

### ISSUE THREAD

**Issue by DoLife** [patrickkfkan/patreon-dl#2]
I`m receiving the following error what can the problem be?

Campaign ID not found in initial data

**Comment by patrickkfkan** [comment]
Hi, does it happen with every campaign you're trying to download from (I'm assuming you're downloading all posts from a campaign or in a collection)? If so, could you provide one of the target URLs here so I can check?

**Comment by colossal-squid** [comment]
Same here

examples: https://www.patreon.com/collection/19157
https://www.patreon.com/karlclews/posts

**Comment by patrickkfkan** [comment]
Hi @colossal-squid , I have updated **v1.1.1** to deal with recent Patreon changes. Please see if this version works.

**Comment by Macro-sudo** [comment]
I am having the same issue. https://www.patreon.com/user/posts?u=[redacted]
redacted due to nsfw link. I cant see this link format as being supported in the read me. Is that why it doesn't work?

Many thanks
