### ISSUE TITLE
 Images without a file type.

### ISSUE THREAD

**Issue by Ninccino** [patrickkfkan/patreon-dl#20]
Occasionally an image would encounter a value of null when checking the id and be given its id or an assortment of like 50-60 characters as the file name. Issue is, the file wouldn’t have any extension connected. No jpg, webp, png, etc. Just a file name.
I don’t believe it was considered an error in logs.

It consistently happened when trying to download an image from a Patreon post that had a video link attached to it and images “embedded” into the post. They weren’t attachments or files.

I don’t have it set to download videos. ffmpeg is installed but not being used. At first I had issues with emojis but I checked issues and switched my node js version to 22 and it fixed them. When I encountered this I tried switching over to 18 LTS. I’m not sure if the issue occurred when I was on 20 LTS. I can check if you’d like.

I didn’t have logging enabled outside of cmd.

**Comment by patrickkfkan** [comment]
Could you provide a link to a post where this happens?

**Comment by Ninccino** [comment]
Like this?

https://www.patreon.com/posts/103145201?utm_campaign=postshare_fan

**Comment by patrickkfkan** [comment]
The link helps. I've fixed this in v1.6.1. Could you please test if the fix works for you? Thanks.

**Comment by Ninccino** [comment]
1.6.1 returns "Data error (campaign ID not found)" whenever I add a url.

CMD = error: Campaign ID not found in initial data of "https://www.patreon.com/guweiz"

I tried using the example config to see if it would work and it still doesn't.

**Comment by patrickkfkan** [comment]
Coincidentally, Patreon made some breaking changes on their end.

Anyway, I just fixed this in v1.6.2.

**Comment by Ninccino** [comment]
Well, that explains it. It works fine now, thank you.
