### ISSUE TITLE
error: PostDownloader: Campaign ID not found in initial data

### ISSUE THREAD

**Issue by dsakura** [patrickkfkan/patreon-dl#21]
Hello! Sorry here I'm again. I tried with 3 different patreon addresses and I all get the same message. I tried updating and the problem persists.

```
info: PostDownloader: Targeting posts by 'cthulhu_architect'
error: PostDownloader: Campaign ID not found in initial data of "https://www.patreon.com/cthulhu_architect"
warn: PostDownloader end with error
```
Thanks

**Comment by patrickkfkan** [comment]
Did you check whether you're on the latest version (v1.6.2)?

**Comment by dsakura** [comment]
I updated yesterday, 1.6.1. I will update again and test, thanks

**Comment by dsakura** [comment]
Great job again, it's working very well! o/ Many thanks!
