### ISSUE TITLE
It hangs when there are special characters like emoji

### ISSUE THREAD

**Issue by tins820** [patrickkfkan/patreon-dl#24]
Here is the log
`Jun 08 16:31:22: info: PostDownloader: Download post #74808706 (🦇Morrigan got a clean shot on camera🦇)
Jun 08 16:31:22: info: PostDownloader: Save post info #74808706`

Here is the target URL
https://www.patreon.com/posts/morrigan-got-on-74808706

**Comment by patrickkfkan** [comment]
Could be this [issue](https://github.com/patrickkfkan/patreon-dl/issues/3). Not a bug in `patreon-dl` but the particular version of Node you're running.

**Comment by tins820** [comment]
it is all good now after updating.

Thanks a lot.
Appreciate your contribution.
