### ISSUE TITLE
URLs only Download first one

### ISSUE THREAD

**Issue by vistaMeow** [patrickkfkan/patreon-dl#26]
using 1.7, when send mutiple URLs to CLI, only first one will be downloaded, the [await ](https://github.com/patrickkfkan/patreon-dl/blob/0432b0f5d2a679dfa7ea70a5b450dd59a96c40b0/src/cli/index.ts#L317C24-L317C29)seems not resolved and the process exit after first download finished.
Using Node.js v20.9.0

**Comment by vistaMeow** [comment]
probablly caused by recent Patreon Front end update. after all file of post downloaded, the `postsFetcher.hasNext` will continue return true and run `postsFetcher.next()`; but this invoke will not return, this `finally` of [Promise](https://github.com/patrickkfkan/patreon-dl/blob/0432b0f5d2a679dfa7ea70a5b450dd59a96c40b0/src/downloaders/PostsFetcher.ts#L386) will not be invoke

**Comment by richbrownio** [comment]
Experiencing the same issue of only the first URL in the urls.txt being downloaded when using a list of post_id URLs.

**Comment by patrickkfkan** [comment]
Updated v2.0.0 which should fix this.

Please feel free to re-open this issue if problem still persists.
