### ISSUE TITLE
Download specific dates

### ISSUE THREAD

**Issue by Dreamkiller711** [patrickkfkan/patreon-dl#29]
Is this possible to scrape before, after or between specific dates? I'd like like this function to be implemented please 🙃

**Comment by patrickkfkan** [comment]
Updated v2.0.0 with this option added (commit 1c116ec).  Refer to `posts.published.after` and `posts.published.before` config options [here](https://github.com/patrickkfkan/patreon-dl/blob/a1c7d6322045b86a790b88be54943e79bb84efaa/example.conf#L203).
