### ISSUE TITLE
Uncaught ReferenceError: patreon is not defined

### ISSUE THREAD

**Issue by ATi1907** [patrickkfkan/patreon-dl#31]
Last login: Thu Sep  5 13:49:21 on ttys000
/usr/local/bin/node ; exit;                                                     
ati@Ati-iMac ~ % /usr/local/bin/node ; exit;
Welcome to Node.js v20.17.0.
Type ".help" for more information.
> patreon-dl
Uncaught ReferenceError: patreon is not defined

**Comment by ATi1907** [comment]
$ npm i -g patreon-dl

Welcome to Node.js v20.17.0.
Type ".help" for more information.
> $ npm i -g patreon-dl
$ npm i -g patreon-dl
  ^^^

Uncaught SyntaxError: Unexpected identifier 'npm'
>

**Comment by patrickkfkan** [comment]
Wrong usage. You're trying to run `patreon-dl` in the Node shell, when you should be doing it in a regular terminal. Also the `$` sign is the command prompt, which you don't need to enter.
