### ISSUE TITLE
Help with commands

### ISSUE THREAD

**Issue by shinkiro25** [patrickkfkan/patreon-dl#32]
How do I improve this command
PatreonDownloader.App.exe --url https://www.patreon.com/AlyxiaAI --download-directory Z:\Patreon\AlyxiaAI 

to make it only download zip attachments and skip existing files?

**Comment by patrickkfkan** [comment]
You are obviously asking in the wrong repo.

**Comment by shinkiro25** [comment]
Yes, my apologies, but I actually remembered that I wanted to ask you how to do this command using your tool.
So basically I wanted to download from https://www.patreon.com/AlyxiaAI and put it into Z:\Patreon\AlyxiaAI
while downloading only zip attachments and skip existing files
