### ISSUE TITLE
FetcherError

### ISSUE THREAD

**Issue by MKO111W** [patrickkfkan/patreon-dl#36]
Hello,I encountered some issues while running it.I can't download.What should I do?

My command:
node ./bin/patreon-dl.js "https://www.patreon.com/posts/jjj-glass-skin-113262021" -c "patreon_locale_code=XXX; patreon_device_id=XXX; __ssid=XXX; session_id=XXX; __stripe_mid=XXX; patreon_locale_code=XXX; cf_clearance=XXX; patreon_currency_pref=USD; __cf_bm=XXX; analytics_session_id=XXX" -o "Z:/X/Q"

The program prompts such an error:
Proceed (Y/n)? Y
Oct 11 20:54:00: info: PostDownloader: Targeting post #113262021
Oct 11 20:54:00: info: PostsFetcher: Fetch target post
Oct 11 20:55:25: error: PostsFetcher: (FetcherError) fetch failed (retried 3 times)
Oct 11 20:55:25: info: PostDownloader: Done downloading post #113262021
Oct 11 20:55:25: info: PostDownloader end

Total 1 targets processed
-------------------------

0: https://www.patreon.com/posts/jjj-glass-skin-113262021
Done

**Comment by patrickkfkan** [comment]
I can download fine from the URL. If you download without cookie (`-c`) , does it give the same error?

What is your environment:

- OS?
- Node version?
- Do you need proxy / VPN for access?

**Comment by MKO111W** [comment]
It will give the same error without cookie (-c),win11  node v20.18.0，I need VPN

**Comment by patrickkfkan** [comment]
Which VPN?

**Comment by MKO111W** [comment]
CLASH

**Comment by patrickkfkan** [comment]
Thought so. See this:

https://github.com/patrickkfkan/patreon-dl/issues/17

I do not know if setting Global mode works, because that person never responded.

**Comment by MKO111W** [comment]
当我改变成全局模式时，也会同样提示这个问题。

**Comment by MKO111W** [comment]
When I change to global mode, the same issue will be prompted.

**Comment by patrickkfkan** [comment]
I don't know exactly how ClashVPN works, but it seems to involve setting proxies which would fail for proxy-unaware apps like `patreon-dl`.  Perhaps you could verify this with your VPN provider, and ask them whether they support TUN mode.

**Comment by MKO111W** [comment]
Okay, I see. Thank you.
