### ISSUE TITLE
content.dir.name.format & content.publishDate output not working

### ISSUE THREAD

**Issue by patg75** [patrickkfkan/patreon-dl#39]
when using
`content.dir.name.format = "{content.publishDate}[ - ]?{content.name}"`
I receive the following error:
```
patreon-dl v2.0.0 Patreon Downloader

Oct 20 23:04:32: error: Failed to get downloader instance: Content directory name format '{content.publishDate}' is invalid (matched against /{content\.id}|{content\.slug}/g)
```
Using .id instead of .publishDate works fine as intended - same as when leaving it empty.

**Comment by patg75** [comment]
PS. Using 
`"{content.publishDate}-{content.id}"`
works nicely but
`"{content.publishDate}-{content.name}"`
doesnt. Same error.

**Comment by patrickkfkan** [comment]
Hello, you are getting the error because `content.dir.name.format` must include at least one of the unique identifiers `content.id` or `content.slug`.
