### ISSUE TITLE
PostDownloader: Post #93397294 is not viewable by current user

### ISSUE THREAD

**Issue by GuyMicciche** [patrickkfkan/patreon-dl#4]
Hello. I keep getting this error message when trying to download. I provide the appropriate cookie patreon_device_id and it is not working. I know the cookie works because i've tried it with other downloader like Stacher. Can you help me diagnose the issue? Thank you!

**Comment by patrickkfkan** [comment]
Hi, did you provide the *full* cookie value as instructed [here](https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie), instead of just `patreon_device_id`?

**Comment by GuyMicciche** [comment]
Thanks I  got it, didn't realize you needed to copy the entire cookie string. Thanks!
