### ISSUE TITLE
I have no idea how to use this

### ISSUE THREAD

**Issue by notKarb** [patrickkfkan/patreon-dl#41]
Can someone make an idiots guide on how to use this please? I am not very good with these types of things and can't find a tutorial or instructions anywhere to use this. Thank you in advance!

**Comment by AydinAlptug** [comment]
See the installation part in the readme:

https://github.com/patrickkfkan/patreon-dl?tab=readme-ov-file#installation

You first need the Node.js first which is a javascript runtime. Then once you install the package from terminal with command:
`$ npm i -g patreon-dl `

you can use the tool with the following command for example to download posts:

`// First download posts by johndoe, followed by posts by janedoe.
$ patreon-dl "https://www.patreon.com/johndoe/posts,https://www.patreon.com/janedoe/posts"`

However in case you want to run it on docker and remove it easily by removing the container you can use this commands (I assume you have installed docker):

`docker run --rm -it --name patreon-dl-container -v "C:\Users\XXX:/app" node:18-alpine sh -c "apk add --no-cache ffmpeg && npm install -g patreon-dl && sh"`

and then move them to your machine:

`docker cp patreon-dl-container:/app/output C:\Users\XXX\output`

**Comment by notKarb** [comment]
I get the message

C:\WINDOWS\system32>$ npm i -g patreon-dl
'$' is not recognized as an internal or external command,
operable program or batch file.

when I try to run the command. I am so useless with this stuff I'm sorry for being so bad

**Comment by AydinAlptug** [comment]
> I get the message
> 
> C:\WINDOWS\system32>$ npm i -g patreon-dl '$' is not recognized as an internal or external command, operable program or batch file.
> 
> when I try to run the command. I am so useless with this stuff I'm sorry for being so bad

I have updated my command. Dollar sign is not part of the command. Just run this part please:

`npm i -g patreon-dl`

**Comment by notKarb** [comment]
I tried with the cookie and get the message 

patreon-dl v2.0.0 Patreon Downloader

Error processing options:  Unknown command-line option '0'
 See usage with '-h' option.



I then tried without the cookie and get this message:

patreon-dl v2.0.0 Patreon Downloader

Error processing options:  Unknown URL: https://www.patreon.com/c/chaesuart/posts
 See usage with '-h' option.

**Comment by AydinAlptug** [comment]
Could you pass the command you use without cookie exactly?

I think you should remove the `/c` from the url that you copied from browser

**Comment by notKarb** [comment]
I don't even know now, I am so confused as to why it won't work

**Comment by patrickkfkan** [comment]
@AydinAlptug , thanks for helping out!

@notKarb , good to know it's working for you!

> I think you should remove the /c from the url that you copied from browser

This will be fixed in the next version (so you won't have to remove the `/c`).

**Comment by notKarb** [comment]
I tried it again today with the input 

npm i -g patreon-dl

and then I posted

patreon-dl "I typed the URL here"

and it only downloaded the previews not the actual posts. Any help again? Sorry guys

**Comment by AydinAlptug** [comment]
> I tried it again today with the input 
> 
> 
> 
> npm i -g patreon-dl
> 
> 
> 
> and then I posted
> 
> 
> 
> patreon-dl "I typed the URL here"
> 
> 
> 
> and it only downloaded the previews not the actual posts. Any help again? Sorry guys

Have you tried to pass the cookie?

https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie

**Comment by notKarb** [comment]
how would I use the cookie after getting it?

**Comment by AydinAlptug** [comment]
> how would I use the cookie after getting it?

You need to pass it as parameter. Check this:

`patreon-dl "https://www.patreon.com/johndoe/posts" - c "COOKIE_STRING"`

It should look like:

`patreon-dl "https://www.patreon.com/johndoe/posts" - c "patreon_device_id=..."`

**Comment by notKarb** [comment]
This worked! Thank you so much!
