### ISSUE TITLE
Am I missing something ? in the post folder only post_info and video_preview

### ISSUE THREAD

**Issue by djvasile** [patrickkfkan/patreon-dl#44]
HI, my goal is to download patreon videos in mp4, I ran the software but unfortunately i only managed to download for each post : post_info and video_preview which contains a short mp4 video and an M3U8 file which after one day stopped working and the thumbnail.

This is an example from status-cache which shows i am using the default config :       "lastDownloadConfig": {
        "include": {
          "lockedContent": true,
          "contentInfo": true,
          "previewMedia": true,
          "contentMedia": true,
          "allMediaVariants": false
        }

**Comment by patrickkfkan** [comment]
Did you pass cookie to `patreon-dl` (`-c` option)?  

[How to obtain cookie](https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie)

**Comment by djvasile** [comment]
I passed the cookies from firefox, i tried to pass from Get cookies.txt LOCALLY chrome extension but it did not work, my main browser chrome also did not work

Perhaps i wasnt succesful with the cookie. I took a look at status-cache and i see that all of the posts show like this, so perhaps :
   "lastTargetInfo": {
        "id": "xxx",
        "isViewable": false,
        "editedAt": "2024-11-08T05:19:50.000+00:00"
      }

**Comment by patrickkfkan** [comment]
So did you try obtaining the cookie using the method in the link I gave you? If you have a valid subscription to the tier you're downloading from, `isViewable` should be `true` and the logs wouldn't say "post is not viewable by current user".

**Comment by patrickkfkan** [comment]
Closing due to lack of response.
