### ISSUE TITLE
barely any idea on how to use

### ISSUE THREAD

**Issue by Xenifiedd** [patrickkfkan/patreon-dl#45]
So i have no previous coding experience or anything like this at all, but i opened up the node.js command prompt, and put in the "npm i -g patreon-dl" part of the code but i have no idea on what to do to download a product after.

**Comment by patrickkfkan** [comment]
So are you able to run `patreon-dl`? Next step would be to [obtain the cookie](https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie), and then run in the command prompt:

```
patreon-dl -c "<cookie you obtained"> "<URL to the product>"
```

**Comment by Xenifiedd** [comment]
oh makes sense now kinda lemme check that
