### ISSUE TITLE
Trying to Download Media in Posts but only downloading Posts

### ISSUE THREAD

**Issue by JY9146** [patrickkfkan/patreon-dl#46]
So I tried to download a Zip file from a post on Patron, but when I downloaded it all I got was the info.txt and post-api.json. I am new here, I used my cookie, and I'm on Mac (although it doesn't appear to affect anything), and I used this command patreon-dl "https://www.patreon.com/johndoe/posts" -c "patreon_device_id=...". PLEASE HELP!

**Comment by JY9146** [comment]
I don't really know how to download a product, I think that's what I'm looking for
I think this is the command I'm looking for, I'm not sure, but if it is how do I find slug and product id?
https://www.patreon.com/<creator>/shop/<slug>-<product_id>

**Comment by JY9146** [comment]
The link for the file I'm trying to download is https://www.patreon.com/posts/wisp-mod-but-my-59331432   if that helps

**Comment by patrickkfkan** [comment]
Check the logs. Do you see "Post #59331432 is not viewable by current user"?

**Comment by JY9146** [comment]
I accidentally reset the terminal before taking a pic of the logs sorry! But from what I remember it didn't have any trouble

**Comment by JY9146** [comment]
I can try running it again and checking the logs

**Comment by JY9146** [comment]
Wait I got it

**Comment by JY9146** [comment]
Nov 22 11:32:32: info: PostDownloader: Download post #59331432 (Wisp Mod - Minecraft, But My Eyes Are Lasers) |
Nov 22 11:32:32: warn: PostDownloader: Post #59331432 is not viewable by current user
Nov 22 11:32:32: info: PostDownloader: Save post info #59331432
Nov 22 11:32:32: info: PostDownloader: Saved post summary to "/Users/(NAME_HERE)/Downloads/patreon-dl-master/ WispJagster - Wisp & Jagster/posts/59331432 - Wisp Mod - Minecraft, But My Eyes Are Lasers/post_info/info.txt" Nov 22 11:32:32: info: PostDownloader: Saved post API data to "/Users/joshuayadidi/Downloads/patreon-dl-master /WispJagster - Wisp & Jagster/posts/59331432 - Wisp Mod - Minecraft, But My Eyes Are Lasers/post_info/post-api
-json"
Nov 22 11:32:32: info: PostDownloader: Download batch created (#31): 0 downloads

**Comment by JY9146** [comment]
So yeah sorry it did say it's not viewable by me

**Comment by JY9146** [comment]
But what do I do?

**Comment by JY9146** [comment]
Well I believe so

**Comment by JY9146** [comment]
I could try the full cookie since I only started off from the patron device Id

**Comment by JY9146** [comment]
Ok did the full cookie with the new command given, but it's still says not viewable by current user

**Comment by JY9146** [comment]
[WispJagster - Wisp & Jagster.zip](https://github.com/user-attachments/files/17875615/WispJagster.-.Wisp.Jagster.zip)
All I got was this

**Comment by JY9146** [comment]
Wait I don't have access in the web browser

**Comment by patrickkfkan** [comment]
`patreon-dl` won't give you higher level of access.

**Comment by JY9146** [comment]
It won't?

**Comment by JY9146** [comment]
So I'm stuck to only get the post info, not the stuff in the post itself :(
