### ISSUE TITLE
Failed to download embedded Youtube video

### ISSUE THREAD

**Issue by msderganc** [patrickkfkan/patreon-dl#51]
Hi,

I'm getting this error using v2.1.1 of patreon-dl and the latest yt-dlp:
`Dec 13 08:18:20: error: PostDownloader: Failed to create download task(s) for item #117891145-embed in post #117891145 -> embedded YouTube video: No src URL found`

I've validated that the link exists and I can click through it on the site with no issues. Some other posts do download correctly - the difference seems to be that the ones that don't work create an embedded-link.txt while the posts that do work create and embedded-video.txt. 

Here's an example of the embedded-link.txt:
```
Embed
--------
Type: linkEmbed
Description: 
HTML: 
Provider: YouTube
provider URL: YouTube
Subject: Queens Of The Stone Age - Make It Wit Chu (Guitar lesson with TAB)
URL: https://youtu.be/uq3XGmXLFeM
```

And embedded-video.txt:
```
Embed
--------
Type: videoEmbed
Description: 
HTML: 
<iframe
    src="https://www.youtube.com/embed/B-U4hyKOPe0"
    class="embedly-embed"
    width="854"
    height="480"
    frameborder="0"
    scrolling="no"
    allowfullscreen
>
</iframe>

Provider: YouTube
provider URL: YouTube
Subject: Polyphia - G.O.A.T. intro (Slow + Play Along Tabs)
URL: https://www.youtube.com/watch?v=B-U4hyKOPe0
```

Prior to this week, it would not generate this error. Everything else downloads correctly.

Thanks!

**Comment by patrickkfkan** [comment]
Fixed in v2.2.0. Please check and report back. Thanks.

**Comment by msderganc** [comment]
Thanks - it seems to be working, but I had to pass yt-dl the cookies from YouTube instead of it automatically getting them. Not sure if that's intended or not.

**Comment by patrickkfkan** [comment]
All `patreon-dl` does is run the external command you specified  in the config. It has no knowledge of what command that is nor the parameters that need to be passed to it. If `yt-dlp` is supposed to obtain YT cookies automatically but doesn't, then that is `yt-dlp`'s problem.

**Comment by msderganc** [comment]
I thought so - I just didn't have to provide the cookies in the past so I wasn't sure if it there was something else going on.

**Comment by patrickkfkan** [comment]
In that case, I'm closing this issue as resolved.
