### ISSUE TITLE
how to use it

### ISSUE THREAD

**Issue by Priyanshp09** [patrickkfkan/patreon-dl#54]
I am not understanding how to use this program as i am new to programming can you please help me or make a video to how to use this.
I want to download pdf from patreon artist shop the link is below
https://www.patreon.com/c/etudetranslations/shop

if you have time can you please help me download them
thank you

**Comment by patrickkfkan** [comment]
`patreon-dl` doesn't require programming knowledge at all. For your use case:

1. Download and install [Node.js](https://nodejs.org/)
2. In a terminal, run `npm i -g patreon-dl`
3. Then [obtain cookie](https://github.com/patrickkfkan/patreon-dl/wiki/How-to-obtain-Cookie)
4. Finally, in a terminal, run `patreon-dl -c "<cookie you obtained>" <URL of product you purchased and want to download>`

**Comment by Priyanshp09** [comment]
getting this error
PS C:\Users\priya> npm i -g patreon-dl
npm : File C:\Program Files\nodejs\npm.ps1 cannot be loaded because running scripts is disabled on this system. For
more information, see about_Execution_Policies at https:/go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:1
+ npm i -g patreon-dl
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by Priyanshp09** [comment]
![Screenshot 2024-12-21 222244](https://github.com/user-attachments/assets/5919f855-f335-471b-b536-45bf4dd67c62)
can't find the cookies either

**Comment by patrickkfkan** [comment]
1. Use the regular shell (`cmd`) if you don't know how to configure permissions in PowerShell.
2. You couldn't find cookies because you didn't follow the instructions. You should filter requests by `posts`:
![image](https://github.com/user-attachments/assets/1ea0b6d5-8bcf-4d51-9028-064cab1941a3)

**Comment by Priyanshp09** [comment]
I was unable to download it 
I think the pdf is not available to download through this method 
if you have time and its possible to download please leave a comment i will send you my mail address so you can send the files
thanks for your help
![Screenshot 2024-12-22 170123](https://github.com/user-attachments/assets/2257d56e-6ab2-4fe1-9e22-172eeebb6018)

**Comment by patrickkfkan** [comment]
Did you not purchase the PDF?
