### ISSUE TITLE
Media Type "Podcast" currently broken / not implimented

### ISSUE THREAD

**Issue by anarcie** [patrickkfkan/patreon-dl#56]
Patreon creator switched media type from "Video" to "Podcast" (Though still a video). There is still a video_preview for these post/media types, but the expected video download isnt there.

### 2024-12-26_039 - The Holiday Episode_039-holiday-118690364
[post-api.json](https://github.com/user-attachments/files/18264016/post-api.json)
[info.txt](https://github.com/user-attachments/files/18264017/info.txt)

### 2024-10-19_AE 29 - Ethan Calls Out Hasan_ae-29-ethan-out-114294994
[info.txt](https://github.com/user-attachments/files/18264023/info.txt)
[post-api.json](https://github.com/user-attachments/files/18264024/post-api.json)

Let me know if there is anything else i can provide.

**Comment by patrickkfkan** [comment]
Hi there! I've just published v2.3.0. Could you check if that version fixes this issue? Thanks.

**Comment by anarcie** [comment]
Just checked and everything is working perfectly again! 

Appreciate the help.

## Logs of the updated post download
### 2024-12-26_039 - The Holiday Episode_039-holiday-118690364
[info.txt](https://github.com/user-attachments/files/18283723/info.txt)
[post-api.json](https://github.com/user-attachments/files/18283724/post-api.json)
