### ISSUE TITLE
What am I doing wrong here? 

### ISSUE THREAD

**Issue by tnmdynamiq** [patrickkfkan/patreon-dl#7]
I am encountering an issue where I can't seem to download audio content from Patreon posts, which seems to occur as if the cookie is incorrect. However, I have verified the cookie directly from my browser's developer tools, ensuring it's correct based on the directions in the Wiki. Can you help identify what I might be overlooking? 

I'm using the `.conf` format for the config file as per the tool's documentation. The tool is downloading images alongside audio, which I don't require. Additionally, the audio files are not in a listenable format. Could there be a configuration or tool-related issue?

### Command I am using in the terminal:
`patreon-dl --config-file /Path/to/config_patreon-dl.conf --cookie "12345678-9abc-def0-1234-56789abcdef0" --out-dir "/Path/to" https://www.patreon.com/creatorname/posts`

### Path I am using to my config file (wasn't sure if I was supposed to use .conf or .json):
`/Path/to/config_patreon-dl.conf`

### Config File Contents
```target.url = https://www.patreon.com/creatorname/posts
cookie = 12345678-9abc-def0-1234-56789abcdef0
use.status.cache = 1
no.prompt = 1
path.to.ffmpeg = /opt/homebrew/opt/ffmpeg@4/bin/ffmpeg

[output]
out.dir = /Path/to/dir
campaign.dir.name.format = "{creator.vanity}[ - ]?{campaign.name}"
content.dir.name.format = "{content.id}[ - ]?{content.name}"
media.filename.format = "{media.filename}"

[include]
locked.content = 1
posts.with.media.type = audio
campaign.info = 1
content.info = 1
content.media = audio

[request]
max.retries = 3
max.concurrent = 10
min.time = 333

[logger.console]
enabled = 1
log.level = info
include.date.time = 1
include.level = 1
include.originator = 1
include.error.stack = 0
date.time.format = "mmm dd HH:MM:ss"
color = 1

**Comment by patrickkfkan** [comment]
Hi,

**Cookie issue**

Did you get `PostDownloader: Post #<id> is not viewable by current user` warning for posts that you should have access to? If so, then your cookie is not working. Verify that you are setting the `cookie` value to the ***full string*** copied from Developer Tools and not just the part given by `patreon_device_id`.

** Images **

Images are downloaded if they are part of campaign or post Info. This is not affected by `content.media` setting which applies to the content itself. You can only skip these images by disabling campaign info (`campaign.info = 0`) and post info (`content.info = 0`).

** Audio format **

The audio formats I've encountered so far are `mp3`, `wav` and `m4a`. All these are mainstream formats. Which format did you get that was not listenable?

**Comment by TetsuyaMitsuru** [comment]
> Hi,
> 
> **Cookie issue**
> 
> Did you get `PostDownloader: Post #<id> is not viewable by current user` warning for posts that you should have access to? If so, then your cookie is not working. Verify that you are setting the `cookie` value to the _**full string**_ copied from Developer Tools and not just the part given by `patreon_device_id`.
> 
> **Images**
> 
> Images are downloaded if they are part of campaign or post Info. This is not affected by `content.media` setting which applies to the content itself. You can only skip these images by disabling campaign info (`campaign.info = 0`) and post info (`content.info = 0`).
> 
> **Audio format**
> 
> The audio formats I've encountered so far are `mp3`, `wav` and `m4a`. All these are mainstream formats. Which format did you get that was not listenable?

Hi, 

I'm having the same problem. I followed your guide on how to get the cookie, and copied the whole string, but it's not working.

This is the command line I entered:

`patreon-dl https://www.patreon.com/DropoutsPod/posts -f F:\Documents\Programs\ffmpeg-6.1.1-full_build\bin\ffmpeg.exe -c patreon_device_id=REDACTED; patreon_location_country_code=GB; patreon_locale_code=en-GB; patreon_currency_pref=USD; a_csrf=REDACTED; __ssid=REDACTED; session_id=REDACTED; __cf_bm=REDACTED; analytics_session_id=REDACTED -o F:\Videos\DropoutsPodcast`

The output I got was:

```
Error processing options: Unknown Command-Line Option '0'
 See usage with '-h' option.
```

I also tried it exclusively with the `analytics_session_id`, `session_id`, and `patreon_device_id`. None worked, I kept getting `Post #<id> is not viewable by current user`. I managed to get PatreonDownloader by AlexCSDev to work with the session_id, but his downloader doesn't organize the downloads into post folders, so it's really messy.

I hope you can help me out.

Regards

**Comment by patrickkfkan** [comment]
@TetsuyaMitsuru , use double-quotes for values with spaces. 

```
patreon-dl -c "patreon_device_id=REDACTED; patreon_location_country_code=GB; patreon_locale_code=en-GB; patreon_currency_pref=USD; a_csrf=REDACTED; __ssid=REDACTED; session_id=REDACTED; __cf_bm=REDACTED; analytics_session_id=REDACTED" ...
```

**Comment by TetsuyaMitsuru** [comment]
> @TetsuyaMitsuru , use double-quotes for values with spaces.
> 
> ```
> patreon-dl -c "patreon_device_id=REDACTED; patreon_location_country_code=GB; patreon_locale_code=en-GB; patreon_currency_pref=USD; a_csrf=REDACTED; __ssid=REDACTED; session_id=REDACTED; __cf_bm=REDACTED; analytics_session_id=REDACTED" ...
> ```

Like this?

`patreon-dl https://www.patreon.com/DropoutsPod/posts -f F:\Documents\Programs\ffmpeg-6.1.1-full_build\bin\ffmpeg.exe -c patreon_device_id="d90b0d6d-19cb-4525-a75d-bd00508d05cd"; patreon_location_country_code="GB"; patreon_locale_code="en-GB"; patreon_currency_pref="USD"; a_csrf="Y0fKLJ_1w8kYqOkVme59DK8U3itp7MHJJXbMMGwbLeY"; __ssid="1086e17ee2fce041a780609102bf2f0"; session_id="paA-q_xb9pGeSTCeBRN0CyA58uaOf9sLEPpR9YZzSVk"; __cf_bm="ccNxloL3skUIV4od_i51XYvZgYEZ24_meOGTk7Tb87o-1706709071-1-AfFWgvU3eSqhsJn1RM+QGDaOfMb+QA7qi1ZROQf4PNzr5WAh0tvsAI9z0GvaRvO45vcCPkhA3qhqtot/kfZHkE29S+FaJrv23i4Tj3o7USvy"; analytics_session_id="d19e6706-5136-49ef-bad0-bea3f91eb847" -o F:\Videos\DropoutsPodcast`

Because, if so, it's not working. I'm getting the same error.

**Comment by TetsuyaMitsuru** [comment]
> @TetsuyaMitsuru , use double-quotes for values with spaces.
> 
> ```
> patreon-dl -c "patreon_device_id=REDACTED; patreon_location_country_code=GB; patreon_locale_code=en-GB; patreon_currency_pref=USD; a_csrf=REDACTED; __ssid=REDACTED; session_id=REDACTED; __cf_bm=REDACTED; analytics_session_id=REDACTED" ...
> ```

It's working now. Thanks for the help!

**Comment by patrickkfkan** [comment]
I have not come across 'mpga'  in my tests, but it should still be playable?

**Comment by patrickkfkan** [comment]
Possible to provide a link to such a post?

**Comment by patrickkfkan** [comment]
A link to a post that gave MPGA file when downloaded with `patreon-dl` , but MP3 when downloaded through the site.

**Comment by patrickkfkan** [comment]
OK, I am able to reproduce this. It turns out the correct download link was used - in this example the downloaded file has MIME type `audio/mpeg`, which should produce a file with `.mp3` extension.  However, the Node module which `patreon-dl` uses to determine extension from MIME type gives `.mpga` for `audio/mpeg`. Hence you get `abcde.mpga` instead of `abcde.mp3`, but the data is actually MP3.  

I will patch this, but for now you can rename the `.mpga` files to `.mp3`.
