### ISSUE TITLE
Filtering Tier

### ISSUE THREAD

**Issue by dsakura** [patrickkfkan/patreon-dl#8]
Hello again... sorry! Maybe this one is more difficult, I hope not, but I think it's the last type of filter that I miss. After downloading the posts I need to delete the lowest tier folders. It's not a huge job, but if the filter is possible, the better, I think.

Great job, congrats and again, many thanks!

**Comment by patrickkfkan** [comment]
Implemented. Please test v1.4.0.

Quick usage: 

```
$ patreon-dl --list-tiers <creator>
```

Mark down the ID of the tiers you want to restrict. Then in your `conf` file:

```
[include]
posts.in.tier = 123456, 987654
```

This will restrict posts to those in tier with ID 123456 or 987654
